### 예치금 중전 테스트 (유저 ID 1번에게 50,000원 충전)
POST http://localhost:8080/api/wallets/1/deposit
Content-Type: application/json


{
  "amount": 50000
}
### 회원가입 테스트
POST http://localhost:8080/api/users/signup
Content-Type: application/json

{
  "email": "test4@naver.com",
  "password": "mypassword123",
  "name": "신입개발자2"
}

### 투자 테스트 (유저 1번이 대출상품 1번에 10000원 투자)
POST http://localhost:8080/api/invests/1/loan/1
Content-Type: application/json

{
  "amount": 10000
}

### 내 투자 내역 조회
GET http://localhost:8080/api/invests/users/1